CREATE TYPE "FacilityType" AS ENUM (
  'CLINIC',
  'HEALTH_CENTRE_II',
  'HEALTH_CENTRE_III',
  'HEALTH_CENTRE_IV',
  'HOSPITAL',
  'LABORATORY',
  'PHARMACY',
  'COMMUNITY_OUTREACH',
  'MOBILE_UNIT'
);

ALTER TABLE "Clinic"
ADD COLUMN "facilityType" "FacilityType" NOT NULL DEFAULT 'CLINIC';
